name: CI

on:
  - push
  - pull_request
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: npm install, build
        run: |
          make install
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
